### ISSUE TITLE
polyglot failed to build

### ISSUE THREAD

**Issue by diegolrz** [psmith3/polyglot-v2#1]
I am trying to deploy polyglot to my DS920+ but the install is not working correctly. Any ideas of what to do to fix it?

Thanks.

`dadmin@xurri-nas:/volume1/docker$  sudo git clone https://github.com/psmith3/pol                                                                                                                                                                             yglot-v2.git
Cloning into 'polyglot-v2'...
remote: Enumerating objects: 4184, done.
remote: Counting objects: 100% (154/154), done.
remote: Compressing objects: 100% (118/118), done.
remote: Total 4184 (delta 95), reused 71 (delta 36), pack-reused 4030
Receiving objects: 100% (4184/4184), 268.76 MiB | 21.77 MiB/s, done.
Resolving deltas: 100% (2515/2515), done.
dadmin@xurri-nas:/volume1/docker$  cd polyglot-v2/
dadmin@xurri-nas:/volume1/docker/polyglot-v2$  ./install.sh
Installing latest polyglot-v2 with mongo...
Running docker-compose up...
Creating volume "polyglot-v2_polyglot-pkgs" with default driver
Pulling mongo (mongo:latest)...
latest: Pulling from library/mongo
25fa05cd42bd: Pull complete
3380d70bde1c: Pull complete
9c5e30e9886d: Pull complete
c6583381983d: Pull complete
7873a2834540: Pull complete
5550b05263ab: Pull complete
f8c53eb02c3e: Pull complete
36d83d0aa258: Pull complete
b6790a091c8a: Pull complete
8cc2814c4956: Pull complete
Digest: sha256:fe44eb6a2ea2bb1548718ec05eb9cb165f1bded37595ebea507bddc413ab99ae
Status: Downloaded newer image for mongo:latest
Building polyglot
Sending build context to Docker daemon  282.3MB

Step 1/12 : FROM node:10-alpine
10-alpine: Pulling from library/node
ddad3d7c1e96: Pulling fs layer
de915e575d22: Pulling fs layer
7150aa69525b: Pulling fs layer
d7aa47be044e: Pulling fs layer
d7aa47be044e: Waiting
7150aa69525b: Verifying Checksum
7150aa69525b: Download complete
ddad3d7c1e96: Verifying Checksum
ddad3d7c1e96: Download complete
d7aa47be044e: Verifying Checksum
d7aa47be044e: Download complete
de915e575d22: Download complete
ddad3d7c1e96: Pull complete
de915e575d22: Pull complete
7150aa69525b: Pull complete
d7aa47be044e: Pull complete
Digest: sha256:dc98dac24efd4254f75976c40bce46944697a110d06ce7fa47e7268470cf2e28
Status: Downloaded newer image for node:10-alpine
 ---> aa67ba258e18
Step 2/12 : EXPOSE 3000
 ---> Running in d8695fc99364
Removing intermediate container d8695fc99364
 ---> 0a3a32110f4c
Step 3/12 : EXPOSE 3001
 ---> Running in 293d1578a17e
Removing intermediate container 293d1578a17e
 ---> a0efc6fc3a02
Step 4/12 : WORKDIR /opt/polyglot-v2/
 ---> Running in fde250b2692c
Removing intermediate container fde250b2692c
 ---> dad909186c2a
Step 5/12 : COPY package.json /opt/polyglot-v2
 ---> beff11068bea
Step 6/12 : COPY package.json /opt
 ---> 3ab4ce7ccefa
Step 7/12 : COPY package-lock.json /opt
 ---> 61e60f5eee2b
Step 8/12 : COPY package-lock.json /opt/polyglot-v2
 ---> 1fe7e88596de
Step 9/12 : RUN apk add --no-cache linux-headers build-base &&          apk add                                                                                                                                                                              --no-cache gcc python3 python3-dev py3-pip bash git ca-certificates wget tzdata                                                                                                                                                                              openssl &&     python3 -m ensurepip &&     rm -r /usr/lib/python*/ensurepip &&                                                                                                                                                                                  pip3 install --upgrade pip setuptools &&     if [ ! -e /usr/bin/pip ]; then l                                                                                                                                                                             n -s pip3 /usr/bin/pip ; fi &&     rm -r /root/.cache &&     cd /opt &&     git                                                                                                                                                                              clone --depth=1 --single-branch --branch master https://github.com/UniversalDevi                                                                                                                                                                             cesInc/polyglot-v2.git &&     npm install
 ---> Running in e921238798c2
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/community/x86_64/APKINDEX.tar.g                                                                                                                                                                             z
(1/17) Installing binutils (2.33.1-r1)
(2/17) Installing libmagic (5.37-r1)
(3/17) Installing file (5.37-r1)
(4/17) Installing gmp (6.1.2-r1)
(5/17) Installing isl (0.18-r0)
(6/17) Installing libgomp (9.3.0-r0)
(7/17) Installing libatomic (9.3.0-r0)
(8/17) Installing mpfr4 (4.0.2-r1)
(9/17) Installing mpc1 (1.1.0-r1)
(10/17) Installing gcc (9.3.0-r0)
(11/17) Installing musl-dev (1.1.24-r3)
(12/17) Installing libc-dev (0.7.2-r0)
(13/17) Installing g++ (9.3.0-r0)
(14/17) Installing make (4.2.1-r2)
(15/17) Installing fortify-headers (1.1-r0)
(16/17) Installing build-base (0.5-r1)
(17/17) Installing linux-headers (4.19.36-r0)
Executing busybox-1.31.1-r10.trigger
OK: 184 MiB in 33 packages
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/community/x86_64/APKINDEX.tar.g                                                                                                                                                                             z
(1/21) Installing ncurses-terminfo-base (6.1_p20200118-r4)
(2/21) Installing ncurses-libs (6.1_p20200118-r4)
(3/21) Installing readline (8.0.1-r0)
(4/21) Installing bash (5.0.11-r1)
Executing bash-5.0.11-r1.post-install
(5/21) Installing ca-certificates (20191127-r2)
(6/21) Installing nghttp2-libs (1.40.0-r1)
(7/21) Installing libcurl (7.67.0-r4)
(8/21) Installing expat (2.2.9-r1)
(9/21) Installing pcre2 (10.34-r1)
(10/21) Installing git (2.24.4-r0)
(11/21) Installing openssl (1.1.1k-r0)
(12/21) Installing libbz2 (1.0.8-r1)
(13/21) Installing libffi (3.2.1-r6)
(14/21) Installing gdbm (1.13-r1)
(15/21) Installing xz-libs (5.2.4-r0)
(16/21) Installing sqlite-libs (3.30.1-r2)
(17/21) Installing python3 (3.8.10-r0)
(18/21) Installing pkgconf (1.6.3-r0)
(19/21) Installing python3-dev (3.8.10-r0)
(20/21) Installing tzdata (2021a-r0)
(21/21) Installing wget (1.20.3-r0)
Executing busybox-1.31.1-r10.trigger
Executing ca-certificates-20191127-r2.trigger
OK: 313 MiB in 54 packages
Looking in links: /tmp/tmpq772vq52
Requirement already satisfied: setuptools in /usr/lib/python3.8/site-packages (5                                                                                                                                                                             6.0.0)
Requirement already satisfied: pip in /usr/lib/python3.8/site-packages (21.1.1)
WARNING: Running pip as root will break packages and permissions. You should ins                                                                                                                                                                             tall packages reliably by using venv: https://pip.pypa.io/warnings/venv
Requirement already satisfied: pip in /usr/lib/python3.8/site-packages (21.1.1)
Collecting pip
  Downloading pip-21.1.3-py3-none-any.whl (1.5 MB)
Requirement already satisfied: setuptools in /usr/lib/python3.8/site-packages (5                                                                                                                                                                             6.0.0)
Collecting setuptools
  Downloading setuptools-57.0.0-py3-none-any.whl (821 kB)
Installing collected packages: setuptools, pip
  Attempting uninstall: setuptools
    Found existing installation: setuptools 56.0.0
    Uninstalling setuptools-56.0.0:
      Successfully uninstalled setuptools-56.0.0
  Attempting uninstall: pip
    Found existing installation: pip 21.1.1
    Uninstalling pip-21.1.1:
      Successfully uninstalled pip-21.1.1
Successfully installed pip-21.1.3 setuptools-57.0.0
WARNING: Running pip as root will break packages and permissions. You should ins                                                                                                                                                                             tall packages reliably by using venv: https://pip.pypa.io/warnings/venv
fatal: destination path 'polyglot-v2' already exists and is not an empty directo                                                                                                                                                                             ry.
The command '/bin/sh -c apk add --no-cache linux-headers build-base &&         a                                                                                                                                                                             pk add --no-cache gcc python3 python3-dev py3-pip bash git ca-certificates wget                                                                                                                                                                              tzdata openssl &&     python3 -m ensurepip &&     rm -r /usr/lib/python*/ensurep                                                                                                                                                                             ip &&     pip3 install --upgrade pip setuptools &&     if [ ! -e /usr/bin/pip ];                                                                                                                                                                              then ln -s pip3 /usr/bin/pip ; fi &&     rm -r /root/.cache &&     cd /opt &&                                                                                                                                                                                  git clone --depth=1 --single-branch --branch master https://github.com/Univer                                                                                                                                                                             salDevicesInc/polyglot-v2.git &&     npm install' returned a non-zero code: 128
ERROR: Service 'polyglot' failed to build
Creating SSL certs & stopping containers...
Stop running containers without removing them.

They can be started again with `docker-compose start`.

Usage: stop [options] [--] [SERVICE...]

Options:
  -t, --timeout TIMEOUT      Specify a shutdown timeout in seconds.
                             (default: 10)
Starting containers...
Building polyglot
Sending build context to Docker daemon  282.3MB

Step 1/12 : FROM node:10-alpine
 ---> aa67ba258e18
Step 2/12 : EXPOSE 3000
 ---> Using cache
 ---> 0a3a32110f4c
Step 3/12 : EXPOSE 3001
 ---> Using cache
 ---> a0efc6fc3a02
Step 4/12 : WORKDIR /opt/polyglot-v2/
 ---> Using cache
 ---> dad909186c2a
Step 5/12 : COPY package.json /opt/polyglot-v2
 ---> Using cache
 ---> beff11068bea
Step 6/12 : COPY package.json /opt
 ---> Using cache
 ---> 3ab4ce7ccefa
Step 7/12 : COPY package-lock.json /opt
 ---> Using cache
 ---> 61e60f5eee2b
Step 8/12 : COPY package-lock.json /opt/polyglot-v2
 ---> Using cache
 ---> 1fe7e88596de
Step 9/12 : RUN apk add --no-cache linux-headers build-base &&          apk add                                                                                                                                                                              --no-cache gcc python3 python3-dev py3-pip bash git ca-certificates wget tzdata                                                                                                                                                                              openssl &&     python3 -m ensurepip &&     rm -r /usr/lib/python*/ensurepip &&                                                                                                                                                                                  pip3 install --upgrade pip setuptools &&     if [ ! -e /usr/bin/pip ]; then l                                                                                                                                                                             n -s pip3 /usr/bin/pip ; fi &&     rm -r /root/.cache &&     cd /opt &&     git                                                                                                                                                                              clone --depth=1 --single-branch --branch master https://github.com/UniversalDevi                                                                                                                                                                             cesInc/polyglot-v2.git &&     npm install
 ---> Running in 52cf7ec6be91
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/community/x86_64/APKINDEX.tar.g                                                                                                                                                                             z
(1/17) Installing binutils (2.33.1-r1)
(2/17) Installing libmagic (5.37-r1)
(3/17) Installing file (5.37-r1)
(4/17) Installing gmp (6.1.2-r1)
(5/17) Installing isl (0.18-r0)
(6/17) Installing libgomp (9.3.0-r0)
(7/17) Installing libatomic (9.3.0-r0)
(8/17) Installing mpfr4 (4.0.2-r1)
(9/17) Installing mpc1 (1.1.0-r1)
(10/17) Installing gcc (9.3.0-r0)
(11/17) Installing musl-dev (1.1.24-r3)
(12/17) Installing libc-dev (0.7.2-r0)
(13/17) Installing g++ (9.3.0-r0)
(14/17) Installing make (4.2.1-r2)
(15/17) Installing fortify-headers (1.1-r0)
(16/17) Installing build-base (0.5-r1)
(17/17) Installing linux-headers (4.19.36-r0)
Executing busybox-1.31.1-r10.trigger
OK: 184 MiB in 33 packages
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/community/x86_64/APKINDEX.tar.g                                                                                                                                                                             z
(1/21) Installing ncurses-terminfo-base (6.1_p20200118-r4)
(2/21) Installing ncurses-libs (6.1_p20200118-r4)
(3/21) Installing readline (8.0.1-r0)
(4/21) Installing bash (5.0.11-r1)
Executing bash-5.0.11-r1.post-install
(5/21) Installing ca-certificates (20191127-r2)
(6/21) Installing nghttp2-libs (1.40.0-r1)
(7/21) Installing libcurl (7.67.0-r4)
(8/21) Installing expat (2.2.9-r1)
(9/21) Installing pcre2 (10.34-r1)
(10/21) Installing git (2.24.4-r0)
(11/21) Installing openssl (1.1.1k-r0)
(12/21) Installing libbz2 (1.0.8-r1)
(13/21) Installing libffi (3.2.1-r6)
(14/21) Installing gdbm (1.13-r1)
(15/21) Installing xz-libs (5.2.4-r0)
(16/21) Installing sqlite-libs (3.30.1-r2)
(17/21) Installing python3 (3.8.10-r0)
(18/21) Installing pkgconf (1.6.3-r0)
(19/21) Installing python3-dev (3.8.10-r0)
(20/21) Installing tzdata (2021a-r0)
(21/21) Installing wget (1.20.3-r0)
Executing busybox-1.31.1-r10.trigger
Executing ca-certificates-20191127-r2.trigger
OK: 313 MiB in 54 packages
Looking in links: /tmp/tmp1lpeo7go
Requirement already satisfied: setuptools in /usr/lib/python3.8/site-packages (5                                                                                                                                                                             6.0.0)
Requirement already satisfied: pip in /usr/lib/python3.8/site-packages (21.1.1)
WARNING: Running pip as root will break packages and permissions. You should ins                                                                                                                                                                             tall packages reliably by using venv: https://pip.pypa.io/warnings/venv
Requirement already satisfied: pip in /usr/lib/python3.8/site-packages (21.1.1)
Collecting pip
  Downloading pip-21.1.3-py3-none-any.whl (1.5 MB)
Requirement already satisfied: setuptools in /usr/lib/python3.8/site-packages (5                                                                                                                                                                             6.0.0)
Collecting setuptools
  Downloading setuptools-57.0.0-py3-none-any.whl (821 kB)
Installing collected packages: setuptools, pip
  Attempting uninstall: setuptools
    Found existing installation: setuptools 56.0.0
    Uninstalling setuptools-56.0.0:
      Successfully uninstalled setuptools-56.0.0
  Attempting uninstall: pip
    Found existing installation: pip 21.1.1
    Uninstalling pip-21.1.1:
      Successfully uninstalled pip-21.1.1
Successfully installed pip-21.1.3 setuptools-57.0.0
WARNING: Running pip as root will break packages and permissions. You should ins                                                                                                                                                                             tall packages reliably by using venv: https://pip.pypa.io/warnings/venv
fatal: destination path 'polyglot-v2' already exists and is not an empty directo                                                                                                                                                                             ry.
The command '/bin/sh -c apk add --no-cache linux-headers build-base &&         a                                                                                                                                                                             pk add --no-cache gcc python3 python3-dev py3-pip bash git ca-certificates wget                                                                                                                                                                              tzdata openssl &&     python3 -m ensurepip &&     rm -r /usr/lib/python*/ensurep                                                                                                                                                                             ip &&     pip3 install --upgrade pip setuptools &&     if [ ! -e /usr/bin/pip ];                                                                                                                                                                              then ln -s pip3 /usr/bin/pip ; fi &&     rm -r /root/.cache &&     cd /opt &&                                                                                                                                                                                  git clone --depth=1 --single-branch --branch master https://github.com/Univer                                                                                                                                                                             salDevicesInc/polyglot-v2.git &&     npm install' returned a non-zero code: 128
ERROR: Service 'polyglot' failed to build
Done. Polyglot v2 should now be running in Docker. Access via webbrowser at http                                                                                                                                                                             s://{docker ip address}:3000
`

**Comment by bleepblorp** [comment]
I tried this on a DS1511+ and a DVA3221 and am seeing the same failure to build.

**Comment by psmith3** [comment]
> I tried this on a DS1511+ and a DVA3221 and am seeing the same failure to build.

Yes, it is broken now. I have come up with a new way to install and need to compile my notes and instructions. It has been a while since I last installed and will see what I can write up. Sorry.

**Comment by psmith3** [comment]
> I am trying to deploy polyglot to my DS920+ but the install is not working correctly. Any ideas of what to do to fix it?
> 
> Thanks.
> 
> `dadmin@xurri-nas:/volume1/docker$ sudo git clone https://github.com/psmith3/pol yglot-v2.git
> Cloning into 'polyglot-v2'...
> remote: Enumerating objects: 4184, done.
> remote: Counting objects: 100% (154/154), done.
> remote: Compressing objects: 100% (118/118), done.
> remote: Total 4184 (delta 95), reused 71 (delta 36), pack-reused 4030
> Receiving objects: 100% (4184/4184), 268.76 MiB | 21.77 MiB/s, done.
> Resolving deltas: 100% (2515/2515), done.
> dadmin@xurri-nas:/volume1/docker$ cd polyglot-v2/
> dadmin@xurri-nas:/volume1/docker/polyglot-v2$ ./install.sh
> Installing latest polyglot-v2 with mongo...
> Running docker-compose up...
> Creating volume "polyglot-v2_polyglot-pkgs" with default driver
> Pulling mongo (mongo:latest)...
> latest: Pulling from library/mongo
> 25fa05cd42bd: Pull complete
> 3380d70bde1c: Pull complete
> 9c5e30e9886d: Pull complete
> c6583381983d: Pull complete
> 7873a2834540: Pull complete
> 5550b05263ab: Pull complete
> f8c53eb02c3e: Pull complete
> 36d83d0aa258: Pull complete
> b6790a091c8a: Pull complete
> 8cc2814c4956: Pull complete
> Digest: sha256:fe44eb6a2ea2bb1548718ec05eb9cb165f1bded37595ebea507bddc413ab99ae
> Status: Downloaded newer image for mongo:latest
> Building polyglot
> Sending build context to Docker daemon 282.3MB
> 
> Step 1/12 : FROM node:10-alpine
> 10-alpine: Pulling from library/node
> ddad3d7c1e96: Pulling fs layer
> de915e575d22: Pulling fs layer
> 7150aa69525b: Pulling fs layer
> d7aa47be044e: Pulling fs layer
> d7aa47be044e: Waiting
> 7150aa69525b: Verifying Checksum
> 7150aa69525b: Download complete
> ddad3d7c1e96: Verifying Checksum
> ddad3d7c1e96: Download complete
> d7aa47be044e: Verifying Checksum
> d7aa47be044e: Download complete
> de915e575d22: Download complete
> ddad3d7c1e96: Pull complete
> de915e575d22: Pull complete
> 7150aa69525b: Pull complete
> d7aa47be044e: Pull complete
> Digest: sha256:dc98dac24efd4254f75976c40bce46944697a110d06ce7fa47e7268470cf2e28
> Status: Downloaded newer image for node:10-alpine
> ---> aa67ba258e18
> Step 2/12 : EXPOSE 3000
> ---> Running in d8695fc99364
> Removing intermediate container d8695fc99364
> ---> 0a3a32110f4c
> Step 3/12 : EXPOSE 3001
> ---> Running in 293d1578a17e
> Removing intermediate container 293d1578a17e
> ---> a0efc6fc3a02
> Step 4/12 : WORKDIR /opt/polyglot-v2/
> ---> Running in fde250b2692c
> Removing intermediate container fde250b2692c
> ---> dad909186c2a
> Step 5/12 : COPY package.json /opt/polyglot-v2
> ---> beff11068bea
> Step 6/12 : COPY package.json /opt
> ---> 3ab4ce7ccefa
> Step 7/12 : COPY package-lock.json /opt
> ---> 61e60f5eee2b
> Step 8/12 : COPY package-lock.json /opt/polyglot-v2
> ---> 1fe7e88596de
> Step 9/12 : RUN apk add --no-cache linux-headers build-base && apk add --no-cache gcc python3 python3-dev py3-pip bash git ca-certificates wget tzdata openssl && python3 -m ensurepip && rm -r /usr/lib/python*/ensurepip && pip3 install --upgrade pip setuptools && if [ ! -e /usr/bin/pip ]; then l n -s pip3 /usr/bin/pip ; fi && rm -r /root/.cache && cd /opt && git clone --depth=1 --single-branch --branch master https://github.com/UniversalDevi cesInc/polyglot-v2.git && npm install
> ---> Running in e921238798c2
> fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/main/x86_64/APKINDEX.tar.gz
> fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/community/x86_64/APKINDEX.tar.g z
> (1/17) Installing binutils (2.33.1-r1)
> (2/17) Installing libmagic (5.37-r1)
> (3/17) Installing file (5.37-r1)
> (4/17) Installing gmp (6.1.2-r1)
> (5/17) Installing isl (0.18-r0)
> (6/17) Installing libgomp (9.3.0-r0)
> (7/17) Installing libatomic (9.3.0-r0)
> (8/17) Installing mpfr4 (4.0.2-r1)
> (9/17) Installing mpc1 (1.1.0-r1)
> (10/17) Installing gcc (9.3.0-r0)
> (11/17) Installing musl-dev (1.1.24-r3)
> (12/17) Installing libc-dev (0.7.2-r0)
> (13/17) Installing g++ (9.3.0-r0)
> (14/17) Installing make (4.2.1-r2)
> (15/17) Installing fortify-headers (1.1-r0)
> (16/17) Installing build-base (0.5-r1)
> (17/17) Installing linux-headers (4.19.36-r0)
> Executing busybox-1.31.1-r10.trigger
> OK: 184 MiB in 33 packages
> fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/main/x86_64/APKINDEX.tar.gz
> fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/community/x86_64/APKINDEX.tar.g z
> (1/21) Installing ncurses-terminfo-base (6.1_p20200118-r4)
> (2/21) Installing ncurses-libs (6.1_p20200118-r4)
> (3/21) Installing readline (8.0.1-r0)
> (4/21) Installing bash (5.0.11-r1)
> Executing bash-5.0.11-r1.post-install
> (5/21) Installing ca-certificates (20191127-r2)
> (6/21) Installing nghttp2-libs (1.40.0-r1)
> (7/21) Installing libcurl (7.67.0-r4)
> (8/21) Installing expat (2.2.9-r1)
> (9/21) Installing pcre2 (10.34-r1)
> (10/21) Installing git (2.24.4-r0)
> (11/21) Installing openssl (1.1.1k-r0)
> (12/21) Installing libbz2 (1.0.8-r1)
> (13/21) Installing libffi (3.2.1-r6)
> (14/21) Installing gdbm (1.13-r1)
> (15/21) Installing xz-libs (5.2.4-r0)
> (16/21) Installing sqlite-libs (3.30.1-r2)
> (17/21) Installing python3 (3.8.10-r0)
> (18/21) Installing pkgconf (1.6.3-r0)
> (19/21) Installing python3-dev (3.8.10-r0)
> (20/21) Installing tzdata (2021a-r0)
> (21/21) Installing wget (1.20.3-r0)
> Executing busybox-1.31.1-r10.trigger
> Executing ca-certificates-20191127-r2.trigger
> OK: 313 MiB in 54 packages
> Looking in links: /tmp/tmpq772vq52
> Requirement already satisfied: setuptools in /usr/lib/python3.8/site-packages (5 6.0.0)
> Requirement already satisfied: pip in /usr/lib/python3.8/site-packages (21.1.1)
> WARNING: Running pip as root will break packages and permissions. You should ins tall packages reliably by using venv: https://pip.pypa.io/warnings/venv
> Requirement already satisfied: pip in /usr/lib/python3.8/site-packages (21.1.1)
> Collecting pip
> Downloading pip-21.1.3-py3-none-any.whl (1.5 MB)
> Requirement already satisfied: setuptools in /usr/lib/python3.8/site-packages (5 6.0.0)
> Collecting setuptools
> Downloading setuptools-57.0.0-py3-none-any.whl (821 kB)
> Installing collected packages: setuptools, pip
> Attempting uninstall: setuptools
> Found existing installation: setuptools 56.0.0
> Uninstalling setuptools-56.0.0:
> Successfully uninstalled setuptools-56.0.0
> Attempting uninstall: pip
> Found existing installation: pip 21.1.1
> Uninstalling pip-21.1.1:
> Successfully uninstalled pip-21.1.1
> Successfully installed pip-21.1.3 setuptools-57.0.0
> WARNING: Running pip as root will break packages and permissions. You should ins tall packages reliably by using venv: https://pip.pypa.io/warnings/venv
> fatal: destination path 'polyglot-v2' already exists and is not an empty directo ry.
> The command '/bin/sh -c apk add --no-cache linux-headers build-base && a pk add --no-cache gcc python3 python3-dev py3-pip bash git ca-certificates wget tzdata openssl && python3 -m ensurepip && rm -r /usr/lib/python*/ensurep ip && pip3 install --upgrade pip setuptools && if [ ! -e /usr/bin/pip ]; then ln -s pip3 /usr/bin/pip ; fi && rm -r /root/.cache && cd /opt && git clone --depth=1 --single-branch --branch master https://github.com/Univer salDevicesInc/polyglot-v2.git && npm install' returned a non-zero code: 128
> ERROR: Service 'polyglot' failed to build
> Creating SSL certs & stopping containers...
> Stop running containers without removing them.
> 
> They can be started again with `docker-compose start`.
> 
> Usage: stop [options] [--] [SERVICE...]
> 
> Options:
> -t, --timeout TIMEOUT Specify a shutdown timeout in seconds.
> (default: 10)
> Starting containers...
> Building polyglot
> Sending build context to Docker daemon 282.3MB
> 
> Step 1/12 : FROM node:10-alpine
> ---> aa67ba258e18
> Step 2/12 : EXPOSE 3000
> ---> Using cache
> ---> 0a3a32110f4c
> Step 3/12 : EXPOSE 3001
> ---> Using cache
> ---> a0efc6fc3a02
> Step 4/12 : WORKDIR /opt/polyglot-v2/
> ---> Using cache
> ---> dad909186c2a
> Step 5/12 : COPY package.json /opt/polyglot-v2
> ---> Using cache
> ---> beff11068bea
> Step 6/12 : COPY package.json /opt
> ---> Using cache
> ---> 3ab4ce7ccefa
> Step 7/12 : COPY package-lock.json /opt
> ---> Using cache
> ---> 61e60f5eee2b
> Step 8/12 : COPY package-lock.json /opt/polyglot-v2
> ---> Using cache
> ---> 1fe7e88596de
> Step 9/12 : RUN apk add --no-cache linux-headers build-base && apk add --no-cache gcc python3 python3-dev py3-pip bash git ca-certificates wget tzdata openssl && python3 -m ensurepip && rm -r /usr/lib/python*/ensurepip && pip3 install --upgrade pip setuptools && if [ ! -e /usr/bin/pip ]; then l n -s pip3 /usr/bin/pip ; fi && rm -r /root/.cache && cd /opt && git clone --depth=1 --single-branch --branch master https://github.com/UniversalDevi cesInc/polyglot-v2.git && npm install
> ---> Running in 52cf7ec6be91
> fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/main/x86_64/APKINDEX.tar.gz
> fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/community/x86_64/APKINDEX.tar.g z
> (1/17) Installing binutils (2.33.1-r1)
> (2/17) Installing libmagic (5.37-r1)
> (3/17) Installing file (5.37-r1)
> (4/17) Installing gmp (6.1.2-r1)
> (5/17) Installing isl (0.18-r0)
> (6/17) Installing libgomp (9.3.0-r0)
> (7/17) Installing libatomic (9.3.0-r0)
> (8/17) Installing mpfr4 (4.0.2-r1)
> (9/17) Installing mpc1 (1.1.0-r1)
> (10/17) Installing gcc (9.3.0-r0)
> (11/17) Installing musl-dev (1.1.24-r3)
> (12/17) Installing libc-dev (0.7.2-r0)
> (13/17) Installing g++ (9.3.0-r0)
> (14/17) Installing make (4.2.1-r2)
> (15/17) Installing fortify-headers (1.1-r0)
> (16/17) Installing build-base (0.5-r1)
> (17/17) Installing linux-headers (4.19.36-r0)
> Executing busybox-1.31.1-r10.trigger
> OK: 184 MiB in 33 packages
> fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/main/x86_64/APKINDEX.tar.gz
> fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/community/x86_64/APKINDEX.tar.g z
> (1/21) Installing ncurses-terminfo-base (6.1_p20200118-r4)
> (2/21) Installing ncurses-libs (6.1_p20200118-r4)
> (3/21) Installing readline (8.0.1-r0)
> (4/21) Installing bash (5.0.11-r1)
> Executing bash-5.0.11-r1.post-install
> (5/21) Installing ca-certificates (20191127-r2)
> (6/21) Installing nghttp2-libs (1.40.0-r1)
> (7/21) Installing libcurl (7.67.0-r4)
> (8/21) Installing expat (2.2.9-r1)
> (9/21) Installing pcre2 (10.34-r1)
> (10/21) Installing git (2.24.4-r0)
> (11/21) Installing openssl (1.1.1k-r0)
> (12/21) Installing libbz2 (1.0.8-r1)
> (13/21) Installing libffi (3.2.1-r6)
> (14/21) Installing gdbm (1.13-r1)
> (15/21) Installing xz-libs (5.2.4-r0)
> (16/21) Installing sqlite-libs (3.30.1-r2)
> (17/21) Installing python3 (3.8.10-r0)
> (18/21) Installing pkgconf (1.6.3-r0)
> (19/21) Installing python3-dev (3.8.10-r0)
> (20/21) Installing tzdata (2021a-r0)
> (21/21) Installing wget (1.20.3-r0)
> Executing busybox-1.31.1-r10.trigger
> Executing ca-certificates-20191127-r2.trigger
> OK: 313 MiB in 54 packages
> Looking in links: /tmp/tmp1lpeo7go
> Requirement already satisfied: setuptools in /usr/lib/python3.8/site-packages (5 6.0.0)
> Requirement already satisfied: pip in /usr/lib/python3.8/site-packages (21.1.1)
> WARNING: Running pip as root will break packages and permissions. You should ins tall packages reliably by using venv: https://pip.pypa.io/warnings/venv
> Requirement already satisfied: pip in /usr/lib/python3.8/site-packages (21.1.1)
> Collecting pip
> Downloading pip-21.1.3-py3-none-any.whl (1.5 MB)
> Requirement already satisfied: setuptools in /usr/lib/python3.8/site-packages (5 6.0.0)
> Collecting setuptools
> Downloading setuptools-57.0.0-py3-none-any.whl (821 kB)
> Installing collected packages: setuptools, pip
> Attempting uninstall: setuptools
> Found existing installation: setuptools 56.0.0
> Uninstalling setuptools-56.0.0:
> Successfully uninstalled setuptools-56.0.0
> Attempting uninstall: pip
> Found existing installation: pip 21.1.1
> Uninstalling pip-21.1.1:
> Successfully uninstalled pip-21.1.1
> Successfully installed pip-21.1.3 setuptools-57.0.0
> WARNING: Running pip as root will break packages and permissions. You should ins tall packages reliably by using venv: https://pip.pypa.io/warnings/venv
> fatal: destination path 'polyglot-v2' already exists and is not an empty directo ry.
> The command '/bin/sh -c apk add --no-cache linux-headers build-base && a pk add --no-cache gcc python3 python3-dev py3-pip bash git ca-certificates wget tzdata openssl && python3 -m ensurepip && rm -r /usr/lib/python*/ensurep ip && pip3 install --upgrade pip setuptools && if [ ! -e /usr/bin/pip ]; then ln -s pip3 /usr/bin/pip ; fi && rm -r /root/.cache && cd /opt && git clone --depth=1 --single-branch --branch master https://github.com/Univer salDevicesInc/polyglot-v2.git && npm install' returned a non-zero code: 128
> ERROR: Service 'polyglot' failed to build
> Done. Polyglot v2 should now be running in Docker. Access via webbrowser at http s://{docker ip address}:3000
> `

Yes, it is broken now. I have come up with a new way to install and need to compile my notes and instructions. It has been a while since I last installed and will see what I can write up. Sorry.
